#!/bin/bash
DIR=$(readlink -f "$(dirname "$0")")

cd "$DIR" || exit 1

function instruct () {
  local title=$1
  local command=$2

    echo -e "\e[0m
\e[1m$title\e[0m
\e[2m$command\e[0m"
}

function requirements () {
  local has_error=0

  if ! which python > /dev/null 2> /dev/null; then
    has_error=1
    instruct "Install python" "pacman -S python"
  fi

  if ! which ansible > /dev/null 2> /dev/null; then
    has_error=1
    instruct "Install ansible" "pacman -S ansible"
  fi

  if ! which ansible-galaxy > /dev/null 2> /dev/null; then
    has_error=1
    instruct "Update ansible" "pacman -S ansible"
  fi

  if [ $has_error -ne 0 ]; then
    exit 1
  fi
}

requirements

python --version | cut -d' ' -f2 | xargs -I{} echo "Python: {}"
ansible --version | head -n 1 | sed -r 's/.*\[.* (.*?)\]$/\1/' | xargs -I{} echo "Ansible: {}"
ansible-galaxy --version | head -n 1 | sed -r 's/.*\[.* (.*?)\]$/\1/' | xargs -I{} echo "Ansible Galaxy: {}"

ansible-galaxy install -r requirements.yml
ansible-playbook -K -i inventory.yml main.yml
