- name: Install Docker and Docker-Compose
  become: yes
  block:
    - name: install
      pacman: name=docker,docker-compose
    - name: enable
      systemd: name=docker enabled=yes state=started

- name: Install scanner
  yay: name=snyk

