- name: CLIs
  block:
    - name: default
      become: yes
      pacman: name=kubectl
    - name: kct
      aur: name=kct-bin
    - name: helm
      become: yes
      pacman: name=helm

- name: Context helpers
  become: yes
  pacman: name=kubectx

- name: Logs visualizer
  aur: name=stern-bin

- name: Cluster scanner
  become: yes
  pacman: name=popeye

- name: Local cluster
  aur: name=rancher-k3d-bin
